image:
  #file: .gitpod.Dockerfile
  file: Dockerfile

 
tasks:
- name: QewdJS setup
  before: echo $PWD && echo " this is a before task "
  #init: cd /opt/qewd && npm install
  command: echo 'You should now be able to start QEWD by typing node qewd'
ports:
  - port: 8080 #Qewd