image:
  #file: .gitpod.Dockerfile
  file: Dockerfile

 
tasks:
- name: QewdJS setup
  before: echo $PWD && echo " this is a before task "
  command: >
    echo $PWD &&
    cd /opt/qewd &&
    npm install &&
    cp /opt/qewd/node_modules/qewd-monitor/www/bundle.js /opt/qewd/www/qewd-monitor &&
    cp /opt/qewd/node_modules/qewd-monitor/www/*.html /opt/qewd/www/qewd-monitor &&
    cp /opt/qewd/node_modules/qewd-monitor/www/*.css /opt/qewd/www/qewd-monitor &&
    cp /opt/qewd/node_modules/ewd-client/lib/proto/ewd-client.js /opt/qewd/www
    npm start
    #npm install -g npm@latest &&
    #npm install &&
    #npm install module-exists &&
    #npm install mg-dbx &&
    #command: npm start
ports:
  - port: 8080 #Qewd